# This is a basic workflow to help you get started with Actions

name: HOWTO_ASEEMBLY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Assembly_server_howto
        run: |
          mkdir -p site/server/
          cat ./flask_server/01_header1.md > ./site/server/index.md
          cat ./flask_server/02_header2.md >> ./site/server/index.md
          cat ./flask_server/03_ssh_keys.md >> ./site/server/index.md
          cat ./flask_server/04_VM_Yandex.md >> ./site/server/index.md
          cat ./flask_server/05_first_connect.md >> ./site/server/index.md
          cat ./flask_server/06_soft_install.md >> ./site/server/index.md
          cat ./flask_server/07_sshd_config.md >> ./site/server/index.md
      
      # Runs a set of commands using the runners shell
      - name: Assembly_index_md
        run: cat README.md > ./site/index.md
      
      # Deploy our file 
      - name: Deploy_to_gh_pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # exclude_assets: '.github'
          publish_dir: ./site
          disable_nojekyll: true
