# This is a basic workflow to help you get started with Actions

name: HOWTO_ASEEMBLY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Assembly how-to files to index.md
      - name: Assembly_server_howto
        run: |
          mkdir -p site/server/
          cat ./flask_server/01_header1.md > ./site/server/index.md
          cat ./flask_server/02_header2.md >> ./site/server/index.md
          cat ./flask_server/03_ssh_keys.md >> ./site/server/index.md
          cat ./flask_server/04_VM_Yandex.md >> ./site/server/index.md
          cat ./flask_server/05_first_connect.md >> ./site/server/index.md
          cat ./flask_server/06_soft_install.md >> ./site/server/index.md
          cat ./flask_server/07_sshd_config.md >> ./site/server/index.md
          cat ./flask_server/08_nginx_install.md >> ./site/server/index.md
          cat ./flask_server/09_end_base_step.md >> ./site/server/index.md
          cat ./flask_server/10_ufw.md >> ./site/server/index.md
          cat ./flask_server/11_a_record.md >> ./site/server/index.md
          cat ./flask_server/12_flask.md >> ./site/server/index.md
          cat ./flask_server/13_gunicorn.md >> ./site/server/index.md
          cat ./flask_server/14_nginx_80_proxy.md >> ./site/server/index.md
          cat ./flask_server/99_footer.md >> ./site/server/index.md

      - name: Assembly_xclip_md
        run: |
          mkdir -p site/xclip/
          cat xclip.md > ./site/xclip/index.md

      - name: Assembly_aliases_md
        run: |
          mkdir -p site/aliases/
          cat aliases.md > ./site/aliases/index.md

      - name: Assembly_keystote_md
        run: |
          mkdir -p site/keystore/
          cat keystore.md > ./site/keystore/index.md

      - name: Assembly_index_md
        run: cat README.md > ./site/index.md

      # Deploy our file
      - name: Deploy_to_gh_pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # exclude_assets: '.github'
          publish_dir: ./site
          enable_jekyll: true
          #disable_nojekyll: true
